# Generated by Django 3.2.4 on 2021-06-29 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='istagram_link',
            new_name='instagram_link',
        ),
    ]
