# Generated by Django 3.2.4 on 2021-06-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_istagram_link_team_instagram_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_info', models.CharField(default='Company Information', max_length=200)),
                ('phone_number', models.IntegerField(max_length=50)),
                ('email_info', models.CharField(max_length=200)),
                ('facebook_main_link', models.CharField(max_length=200)),
                ('twitter_main_link', models.CharField(max_length=200)),
                ('instagram_main_link', models.CharField(max_length=200)),
                ('linkedin_main_link', models.CharField(max_length=200)),
            ],
        ),
    ]
