# Generated by Django 3.2.4 on 2021-06-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_companyinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='email_info',
            field=models.EmailField(default='contact@carzon.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='facebook_main_link',
            field=models.CharField(default='https//:facebook.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='instagram_main_link',
            field=models.CharField(default='https//:instagram.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='linkedin_main_link',
            field=models.CharField(default='https//:linkedin.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='phone_number',
            field=models.CharField(default='+81', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='twitter_main_link',
            field=models.CharField(default='https//:twitter.com', max_length=200),
        ),
    ]
